-- Additive migration. Leaves the existing CRM public schema unchanged.
BEGIN;
CREATE SCHEMA IF NOT EXISTS procurement;
REVOKE ALL ON SCHEMA procurement FROM PUBLIC, anon, authenticated;
SET LOCAL search_path TO procurement, pg_catalog;
CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY);
INSERT INTO schema_version VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, name TEXT NOT NULL, password TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('ADMIN','PROCUREMENT','SALES','PACKING')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory(variant TEXT PRIMARY KEY, physical INTEGER NOT NULL DEFAULT 0 CHECK(physical>=0),
 damaged INTEGER NOT NULL DEFAULT 0 CHECK(damaged>=0), availability TEXT NOT NULL DEFAULT 'AMBER' CHECK(availability IN ('GREEN','AMBER','RED')),
 fresh_photos INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY, number TEXT NOT NULL, customer TEXT NOT NULL, source TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'WAITING_FOR_PROCUREMENT', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 source_updated_at TEXT, fulfillment_state TEXT, note TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS order_lines(id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), variant TEXT NOT NULL,
 quantity INTEGER NOT NULL CHECK(quantity>0), picked INTEGER NOT NULL DEFAULT 0, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id),
 line_id TEXT NOT NULL REFERENCES order_lines(id), variant TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0),
 status TEXT NOT NULL CHECK(status IN ('ACTIVE','RELEASED','SHIPPED')), created_at TEXT NOT NULL, released_at TEXT);
CREATE INDEX IF NOT EXISTS reserved_variant ON reservations(variant,status);
CREATE TABLE IF NOT EXISTS requirements(id TEXT PRIMARY KEY, line_id TEXT NOT NULL UNIQUE REFERENCES order_lines(id), variant TEXT NOT NULL,
 shortage INTEGER NOT NULL, outstanding INTEGER NOT NULL, priority INTEGER NOT NULL DEFAULT 0,
 assigned_vendor TEXT, required_by TEXT, notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS batches(id TEXT PRIMARY KEY, variant TEXT NOT NULL, vendor TEXT NOT NULL, supplier_sku TEXT NOT NULL,
 quantity INTEGER NOT NULL CHECK(quantity>0), required_for_orders INTEGER NOT NULL, unit_paise INTEGER NOT NULL CHECK(unit_paise>=0),
 status TEXT NOT NULL CHECK(status IN ('PURCHASED','IN_TRANSIT','RECEIVED')), payment TEXT NOT NULL,
 received INTEGER NOT NULL DEFAULT 0 CHECK(received>=0), short_closed INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, transit_at TEXT, received_at TEXT, expected_at TEXT,
 invoice TEXT, notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS goods_receipts(id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES batches(id),
 good INTEGER NOT NULL, damaged INTEGER NOT NULL, wrong INTEGER NOT NULL, condition TEXT NOT NULL, note TEXT,
 user_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_movements(id TEXT PRIMARY KEY, variant TEXT NOT NULL, quantity_delta INTEGER NOT NULL,
 damaged_delta INTEGER NOT NULL DEFAULT 0, movement_type TEXT NOT NULL, reference_id TEXT NOT NULL, user_id TEXT NOT NULL, note TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS price_history(id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES batches(id), variant TEXT NOT NULL,
 vendor TEXT NOT NULL, unit_paise INTEGER NOT NULL, quantity INTEGER NOT NULL, user_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payment_events(id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES batches(id), previous TEXT, current TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS issues(id TEXT PRIMARY KEY, entity TEXT NOT NULL, entity_id TEXT NOT NULL, issue_type TEXT NOT NULL,
 note TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, resolved_at TEXT, resolution TEXT);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY, product_id TEXT NOT NULL, variant TEXT NOT NULL, batch_id TEXT NOT NULL REFERENCES batches(id),
 vendor TEXT NOT NULL, uploaded_by TEXT NOT NULL, uploaded_at TEXT NOT NULL, filename TEXT NOT NULL, view_type TEXT NOT NULL,
 source_type TEXT NOT NULL DEFAULT 'REAL_PROCUREMENT_PHOTO', approval TEXT NOT NULL DEFAULT 'PENDING_REVIEW',
 customer_visible_approved INTEGER NOT NULL DEFAULT 0, is_primary INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS verification_tasks(id TEXT PRIMARY KEY, product_id TEXT NOT NULL, prompt TEXT NOT NULL,
 answer TEXT, created_at TEXT NOT NULL, completed_at TEXT, completed_by TEXT);
CREATE TABLE IF NOT EXISTS audit_events(seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL, timestamp TEXT NOT NULL,
 entity TEXT NOT NULL, entity_id TEXT NOT NULL, previous TEXT, current TEXT, action TEXT NOT NULL, reason TEXT);
CREATE TABLE IF NOT EXISTS catalog_outbox(seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency(key TEXT PRIMARY KEY, fingerprint TEXT NOT NULL, result TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS webhook_inbox(id TEXT PRIMARY KEY, topic TEXT NOT NULL, shop TEXT NOT NULL, payload TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'PENDING', error TEXT, created_at TEXT NOT NULL, processed_at TEXT);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO settings VALUES('purchased_hours','48') ON CONFLICT DO NOTHING;
INSERT INTO settings VALUES('transit_hours','72') ON CONFLICT DO NOTHING;
INSERT INTO settings VALUES('ready_hours','24') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS login_attempts (key TEXT PRIMARY KEY, count INTEGER NOT NULL, started_at DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS catalog_projection (variant TEXT PRIMARY KEY, payload TEXT NOT NULL, synced_at TEXT NOT NULL);
CREATE OR REPLACE FUNCTION procurement.reject_history_mutation() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN RAISE EXCEPTION 'Procurement history is immutable'; END;
$$;
DROP TRIGGER IF EXISTS immutable_history ON audit_events;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION procurement.reject_history_mutation();
DROP TRIGGER IF EXISTS immutable_history ON inventory_movements;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON inventory_movements FOR EACH ROW EXECUTE FUNCTION procurement.reject_history_mutation();
DROP TRIGGER IF EXISTS immutable_history ON price_history;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON price_history FOR EACH ROW EXECUTE FUNCTION procurement.reject_history_mutation();
DROP TRIGGER IF EXISTS immutable_history ON payment_events;
CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON payment_events FOR EACH ROW EXECUTE FUNCTION procurement.reject_history_mutation();
ALTER TABLE schema_version ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON schema_version FROM PUBLIC, anon, authenticated;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON users FROM PUBLIC, anon, authenticated;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON inventory FROM PUBLIC, anon, authenticated;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON orders FROM PUBLIC, anon, authenticated;
ALTER TABLE order_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON order_lines FROM PUBLIC, anon, authenticated;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON reservations FROM PUBLIC, anon, authenticated;
ALTER TABLE requirements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON requirements FROM PUBLIC, anon, authenticated;
ALTER TABLE batches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON batches FROM PUBLIC, anon, authenticated;
ALTER TABLE goods_receipts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON goods_receipts FROM PUBLIC, anon, authenticated;
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON inventory_movements FROM PUBLIC, anon, authenticated;
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON price_history FROM PUBLIC, anon, authenticated;
ALTER TABLE payment_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON payment_events FROM PUBLIC, anon, authenticated;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON issues FROM PUBLIC, anon, authenticated;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON assets FROM PUBLIC, anon, authenticated;
ALTER TABLE verification_tasks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON verification_tasks FROM PUBLIC, anon, authenticated;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON audit_events FROM PUBLIC, anon, authenticated;
ALTER TABLE catalog_outbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON catalog_outbox FROM PUBLIC, anon, authenticated;
ALTER TABLE idempotency ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON idempotency FROM PUBLIC, anon, authenticated;
ALTER TABLE webhook_inbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON webhook_inbox FROM PUBLIC, anon, authenticated;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON settings FROM PUBLIC, anon, authenticated;
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON login_attempts FROM PUBLIC, anon, authenticated;
ALTER TABLE catalog_projection ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON catalog_projection FROM PUBLIC, anon, authenticated;

-- No public read policies: objects are served only after application authentication.
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES ('procurement-private','procurement-private',false,4194304,ARRAY['image/jpeg'])
ON CONFLICT (id) DO NOTHING;
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM storage.buckets WHERE id='procurement-private' AND public) THEN
  RAISE EXCEPTION 'Existing procurement-private bucket is public; review before continuing';
 END IF;
END $$;
COMMIT;
