import type { Activity, AppUser, FollowupTask, Lead, RecoveredOrder } from "./types";
import { scoreBrowserLead } from "./stage";

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60000).toISOString();
const future = (minutesAhead: number) => new Date(now.getTime() + minutesAhead * 60000).toISOString();

export const demoUsers: AppUser[] = [
  {
    id: "user-admin",
    name: "Aditi Admin",
    email: "admin@example.com",
    role: "admin",
    created_at: iso(20000)
  },
  {
    id: "user-sales-1",
    name: "Rahul Sales",
    email: "rahul@example.com",
    role: "salesperson",
    created_at: iso(19000)
  },
  {
    id: "user-sales-2",
    name: "Meera Sales",
    email: "meera@example.com",
    role: "salesperson",
    created_at: iso(18500)
  }
];

export const demoLeads: Lead[] = [
  {
    id: "lead-init",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "INIT - checkout opened",
    normalized_stage: "INIT",
    lead_score: 20,
    priority: "P3 Nurture",
    customer_name: "Neha Kapoor",
    phone: "+919810000001",
    email: "neha@example.com",
    city: "Delhi",
    state: "Delhi",
    buyer_type: null,
    product_names: "Vitamin C Serum",
    product_url: "https://brand.example/products/vitamin-c-serum",
    checkout_url: "https://checkout.shopify.com/init-001",
    recovery_url: "https://brand.example/cart/recover/init-001",
    cart_value: 899,
    first_seen_at: iso(70),
    assigned_to: "user-sales-1",
    current_status: "new",
    last_contacted_at: null,
    next_follow_up_at: null,
    total_call_attempts: 0,
    total_whatsapp_attempts: 0,
    total_touch_count: 0,
    created_at: iso(70),
    updated_at: iso(70)
  },
  {
    id: "lead-phone",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "Phone received",
    normalized_stage: "Phone received",
    lead_score: 40,
    priority: "P3 Nurture",
    customer_name: "Arjun Rao",
    phone: "+919810000002",
    email: "arjun@example.com",
    city: "Bengaluru",
    state: "Karnataka",
    buyer_type: "Normal customer",
    product_names: "Protein Bar Trial Pack",
    product_url: "https://brand.example/products/protein-bars",
    checkout_url: "https://checkout.shopify.com/phone-002",
    recovery_url: "https://brand.example/cart/recover/phone-002",
    cart_value: 499,
    first_seen_at: iso(220),
    assigned_to: "user-sales-2",
    current_status: "contacted",
    last_contacted_at: iso(160),
    next_follow_up_at: future(90),
    total_call_attempts: 1,
    total_whatsapp_attempts: 1,
    total_touch_count: 2,
    created_at: iso(220),
    updated_at: iso(150)
  },
  {
    id: "lead-otp",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "OTP verified / customer authenticated",
    normalized_stage: "OTP verified",
    lead_score: 60,
    priority: "P2 Warm",
    customer_name: "Priya Menon",
    phone: "+919810000003",
    email: "priya@example.com",
    city: "Kochi",
    state: "Kerala",
    buyer_type: null,
    product_names: "Hair Growth Kit",
    product_url: "https://brand.example/products/hair-growth-kit",
    checkout_url: "https://checkout.shopify.com/otp-003",
    recovery_url: "https://brand.example/cart/recover/otp-003",
    cart_value: 2499,
    first_seen_at: iso(390),
    assigned_to: "user-sales-1",
    current_status: "new",
    last_contacted_at: null,
    next_follow_up_at: null,
    total_call_attempts: 0,
    total_whatsapp_attempts: 1,
    total_touch_count: 1,
    created_at: iso(390),
    updated_at: iso(380)
  },
  {
    id: "lead-address",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "Address screen reached",
    normalized_stage: "Address screen",
    lead_score: 75,
    priority: "P2 Warm",
    customer_name: "Kabir Sharma",
    phone: "+919810000004",
    email: "kabir@example.com",
    city: "Mumbai",
    state: "Maharashtra",
    buyer_type: "Interior designer",
    product_names: "Sneaker Care Bundle",
    product_url: "https://brand.example/products/sneaker-care",
    checkout_url: "https://checkout.shopify.com/address-004",
    recovery_url: "https://brand.example/cart/recover/address-004",
    cart_value: 1799,
    first_seen_at: iso(130),
    assigned_to: "user-sales-2",
    current_status: "follow_up",
    last_contacted_at: iso(100),
    next_follow_up_at: iso(20),
    total_call_attempts: 2,
    total_whatsapp_attempts: 1,
    total_touch_count: 3,
    created_at: iso(130),
    updated_at: iso(90)
  },
  {
    id: "lead-order",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "Order screen",
    normalized_stage: "Order screen",
    lead_score: 90,
    priority: "P1 Hot",
    customer_name: "Sara Ali",
    phone: "+919810000005",
    email: "sara@example.com",
    city: "Hyderabad",
    state: "Telangana",
    buyer_type: null,
    product_names: "Premium Skincare Combo",
    product_url: "https://brand.example/products/skincare-combo",
    checkout_url: "https://checkout.shopify.com/order-005",
    recovery_url: "https://brand.example/cart/recover/order-005",
    cart_value: 3499,
    first_seen_at: iso(115),
    assigned_to: "user-sales-1",
    current_status: "new",
    last_contacted_at: null,
    next_follow_up_at: null,
    total_call_attempts: 0,
    total_whatsapp_attempts: 0,
    total_touch_count: 0,
    created_at: iso(115),
    updated_at: iso(115)
  },
  {
    id: "lead-payment",
    source: "google_sheet",
    source_detail: "Bliss and Birch",
    raw_stage: "Payment initiated - Razorpay opened",
    normalized_stage: "Payment initiated",
    lead_score: 100,
    priority: "P1 Hot",
    customer_name: "Dev Patel",
    phone: "+919810000006",
    email: "dev@example.com",
    city: "Ahmedabad",
    state: "Gujarat",
    buyer_type: null,
    product_names: "Wireless Massage Gun",
    product_url: "https://brand.example/products/massage-gun",
    checkout_url: "https://checkout.shopify.com/payment-006",
    recovery_url: "https://brand.example/cart/recover/payment-006",
    cart_value: 5999,
    first_seen_at: iso(25),
    assigned_to: "user-sales-2",
    current_status: "new",
    last_contacted_at: null,
    next_follow_up_at: null,
    total_call_attempts: 0,
    total_whatsapp_attempts: 0,
    total_touch_count: 0,
    created_at: iso(25),
    updated_at: iso(25)
  },
  {
    id: "lead-browser",
    source: "shiprocket_csv",
    source_detail: "Shiprocket Engage 360",
    raw_stage: "Browser lead",
    normalized_stage: "Phone received",
    lead_score: scoreBrowserLead({
      product_names: "Copper Bottle",
      product_url: "https://brand.example/products/copper-bottle"
    }),
    priority: "P3 Nurture",
    customer_name: "Isha Jain",
    phone: "+919810000007",
    email: null,
    city: "Jaipur",
    state: "Rajasthan",
    buyer_type: null,
    product_names: "Copper Bottle",
    product_url: "https://brand.example/products/copper-bottle",
    checkout_url: null,
    recovery_url: null,
    cart_value: null,
    first_seen_at: iso(55),
    assigned_to: "user-sales-1",
    current_status: "new",
    last_contacted_at: null,
    next_follow_up_at: future(1440),
    total_call_attempts: 0,
    total_whatsapp_attempts: 1,
    total_touch_count: 1,
    created_at: iso(55),
    updated_at: iso(55)
  }
];

export const demoActivities: Activity[] = [
  {
    id: "act-phone-1",
    lead_id: "lead-phone",
    user_id: "user-sales-2",
    activity_type: "call",
    outcome: "not_connected",
    note: "No answer. WhatsApp recovery link sent.",
    next_follow_up_at: future(90),
    created_at: iso(160)
  },
  {
    id: "act-address-1",
    lead_id: "lead-address",
    user_id: "user-sales-2",
    activity_type: "call",
    outcome: "interested",
    note: "Customer asked for delivery estimate before payment.",
    next_follow_up_at: iso(20),
    created_at: iso(100)
  }
];

export const demoFollowups: FollowupTask[] = [
  {
    id: "follow-address-1",
    lead_id: "lead-address",
    assigned_to: "user-sales-2",
    due_at: iso(20),
    status: "missed",
    followup_number: 2,
    created_at: iso(100),
    completed_at: null
  },
  {
    id: "follow-phone-1",
    lead_id: "lead-phone",
    assigned_to: "user-sales-2",
    due_at: future(90),
    status: "pending",
    followup_number: 2,
    created_at: iso(160),
    completed_at: null
  }
];

export const demoRecoveredOrders: RecoveredOrder[] = [];
